version: '3'
services:
  app:
    image: your-dockerhub-username/my-node-app:latest
    container_name: node-app
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=production
    restart: always
