version: '3'
services:
  app:
    image: durlavbose/node-x-docker:latest
    container_name: node-x-docker-test
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=production
    restart: always
