version: '3.8'
services:
  app:
    image: durlavbose/node-x-docker
    container_name: node-app
    ports:
      - "${PORT}:3000"  # Use environment variable for port
    environment:
      MONGODB_URI: ${MONGODB_URI}
      PORT: ${PORT}
      MONGODB_DB: ${MONGODB_DB}
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
